### ISSUE TITLE
docker template

### ISSUE THREAD

**Issue by ihatov08** [wmegane/rails_template#1]
Dockerfile
```
FROM ruby:2.3.1
ENV LANG C.UTF-8
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs fonts-takao imagemagick
RUN mkdir /myapp
WORKDIR /myapp
ADD Gemfile /myapp/Gemfile
ADD Gemfile.lock /myapp/Gemfile.lock
RUN bundle install
ADD . /myapp
```

```yml
# docker-compose.yml
version: '2'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb-ft-min-token-size=2
    volumes:
      - ./db/mysql_data:/var/lib/mysql
  redis:
    image: redis
  app:
    build: .
    environment:
      MYAPP_DATABASE_USERNAME: root
      MYAPP_DATABASE_PASSWORD: "root"
      MYAPP_DATABASE_HOST: db
      MYAPP_DATABASE_SOCKET: /var/run/mysqld/mysqld.sock
      MYAPP_REDIS_URL: redis://redis:6379
  api:
    extends:
      service: app
    command: sh -c 'rm tmp/pids/* || true && bundle exec rails s -p 3000 -b 0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    links:
      - db
      - redis
    tty: true
    stdin_open: true
  job:
    extends:
      service: app
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/myapp
    links:
      - db
      - redis
```

```
# .gitignore
# add↓
/db/mysql_data
```

```yml
# database.yml

default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  username: <%= ENV.fetch('MYAPP_DATABASE_USERNAME') %>
  password: <%= ENV.fetch('MYAPP_DATABASE_PASSWORD') %>
  socket: <%= ENV.fetch('MYAPP_DATABASE_SOCKET') %>
  host: <%= ENV.fetch('MYAPP_DATABASE_HOST') %>

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  pool: 64
  database: myapp_production
```

```ruby
#config/initializers/sidekiq.rb

url = { url: "#{ENV['MYAPP_REDIS_URL']}" }

Sidekiq.configure_client do |config|
  config.redis = url
end

Sidekiq.configure_server do |config|
  config.redis = url
end
```

```yml
# sidekiq.yml

:concurrency: 5
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
production:
  :concurrency: 5
:queues:
  - default
  - mailers
  - scheduler
  - slack
```
