### ISSUE TITLE
circle ci 追加設定

### ISSUE THREAD

**Issue by nashirox** [wmegane/rails_template#10]
CircleCiのconfigテンプレを活用したsite handlerの設定ファイル

```
# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2

jobs:
  build:
    working_directory: ~/myproject

    docker:
       - image: circleci/ruby:2.4.1-node-browsers
         environment:
           RAILS_ENV: test
           DATABASE_USERNAME: root
           DATABASE_PASSWORD: ""
           DATABASE_SOCKET: null
           DATABASE_HOST: '127.0.0.1'

       - image: circleci/mysql:5.7
         environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          - MYSQL_ROOT_HOST: '%'

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: bundle exec rails db:setup

      # run tests!
      - run: bundle exec rails test

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
```
